### ISSUE TITLE
Rewrite all texts to English

### ISSUE THREAD

**Issue by ondrejmirtes** [travelbot/travelbot#2]
We have a new member in our team, he's from Spain, so we need to start communicate in English.

This includes:
README.md in travelbot repository, two wiki pages and a few messages at Basecamp.

**Comment by dusekpe4** [comment]
I will do it tomorrow, tonight im busy

**Comment by ondrejmirtes** [comment]
Issue is closed after it's done, not before.

**Comment by ondrejmirtes** [comment]
Basecamp messages are not translated yet.

**Comment by PetrVales** [comment]
I have translated it.

**Comment by jff15** [comment]
thank u so much! :)
